<?php

class Inkl_Check24_Test_Unit_Helper_Street extends EcomDev_PHPUnit_Test_Case
{
	/** @var Inkl_Check24_Helper_Street */
	private $helper;

	protected function setUp()
	{
		parent::setUp(); // TODO: Change the autogenerated stub

		$this->helper = Mage::helper('inkl_check24/street');
	}

	/**
	 * @dataProvider testSplitStreetDataProvider
	 * @param string $street
	 * @param array $expected
	 */
	public function testSplitStreet($street, $expected)
	{
		$this->assertSame($expected, $this->helper->splitStreet($street));
	}

	public function testSplitStreetDataProvider()
	{
		return [
			['Straße 1', ['Straße', '1']],
			['Straße 1a', ['Straße', '1a']],
			['Straße 1 a', ['Straße', '1a']],
			['Straße', ['Straße', '-']],
			['Neue Straße ', ['Neue Straße', '-']],
			['Neue Straße 32 ', ['Neue Straße', '32']],
		];
	}

}
